name: ⭐ Feature Request
description: Share Youur Ideas To Improve OwnDroid
title: "Feature Request: "
labels: enhancement

body:
  - type: textarea
    id: describe
    attributes:
      label: Describe Your Idea
      description: What feature or improvement would you like to see in OwnDroid ?
      placeholder: |
        Please be as specific as possible about:
        - What you want to Achieve
        - Why this feature would be useful
        - How you Envision it working
    validations:
      required: true
